[package]
name = "nobg"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda = ["ort/cuda"]
rocm = ["ort/rocm"]
coreml = ["ort/coreml"]
directml = ["ort/directml"]

[dependencies]
axum = { version = "0.8", features = ["multipart"] }
axum-embed = "0.1"
base64 = "0.22"
bytes = "1"
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
directories = "6.0.0"
fmtsize = "0.1.2"
image = "0.25.6"
indicatif = "0.17.11"
ndarray = "0.17.2"
ort = "2.0.0-rc.6"
reqwest = { version = "0.12.20", features = ["blocking"] }
rust-embed = "8.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs"] }
url = "2.5.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dev-dependencies]
futures = "0.3"
